.\" Manpage for hidemego.
.TH HIDEMEGO 1 "29 Sept 2021" "1.0" "hidemego man page"
.SH NAME
.B hidemego \- Tor Transparent Proxy to Anonymize Your System
.SH SYNOPSIS
.B hidemego
.B start
[
.I options
]

.B hidemego
.B new

.B hidemego
.B stop


.SH OPTIONS
.B hidemego
.I start
&&
.I stop

[
.B -cport
:
.I int
\-\ Sets Tor Control Port (default 9052)
]
[
.B -dport
:
.I int
\-\ Sets DNS Port (default 5354)
]
[
.B -sdport
:
.I int
\-\ Sets Socks Destination Port (default 9051)
]
[
.B -saport
:
.I int
\-\ Sets Socks Authentication Port (default 9050)
]
[
.B -tport
:
.I int
\-\ Sets Tor Transport Port (default 9040)
]
[
.B -id 
:
.I int
\-\ Sets Tor User ID 
]
[
.B -user
:
.I string
\-\ Sets Tor User (default: Tor system default)
]
[
.B -pass
:
.I string
\-\ Sets Tor Control Auth Password 
]
[
.B -ifaces
:
.I string
\-\ Sets Interface that MUST change MAC Address (separed by comma if multiple interfaces)
]
[
.B -no5
:
.I bool
\-\ Excludes Nodes from 5 eyes countries (default: false)
]
[
.B -no9
:
.I bool 
\-\ Excludes Nodes from 9 eyes countries (default: false)
]
[
.B -no14
:
.I bool
\-\ Excludes Nodes from 14 eyes countries (default: false)
]
[
.B -no14p
:
.I bool 
\-\ Excludes Nodes from 14 eyes countries and others dangerous countries 
]
[
.B -nok
:
.I bool
\-\ Prevents Changes on Kernel
]


.SH DESCRIPTION
hidemego is a network application useful to anonymize the traffic of linux servers and workstations.
The software uses the technique called Transparent Proxy to route all network connections made by the machine on the Tor network, including DNS queries. In this way, hidemego makes it almost impossible to track any program on the machine that makes network connections.

.SH EXAMPLES

Run `hidemego start` as root to anonymize your system. Without any argoument hidemego will find your Tor ID and Tor User.

Run `hidemego start -no5="true"` as root to start hidemego and exclude nodes from 5 eyes countries.

Run `hidemego\ new` as root to change your IP address by sending an HUP signal to Tor or NEWNYM signal via telnet to Tor (uses netcat).

Run\ `hidemego\ stop` as root to stop hidemego and remove related data, config and directories associated with it. This action will revert the anonymization and give your ISP IP address back to the machine.
.SH FILES & DIRECTORIES
.B \-\ /var/lib/tor/hidemego
| Hidemego Tor's directory

.B \-\ /root/.config/hidemego
| Used as storage for hidemego configurations

.B \-\ /etc/tor/hidemego.torrc
| A torrc generated by hidemego to anonymize the system

.B \-\ /etc/resolv.conf.orig
| To save and restore the original resolv.conf 

.SH DISCLAIMER
.I The author of this software assumes no responsibility for the use of this software to perform actions that do not comply with the law and/or damage property and/or individuals.

.I Using this software you take full responsibility for your actions.

.SH SEE ALSO
.B TOR(1)

.I https://github.com/multiversecoder/hidemego
.SH BUGS
No known bugs.
.SH AUTHOR
Adriano Romanazzo
.SH COPYRIGHT
Copyright (c) 2021-present, Adriano Romanazzo
.SH LICENSE
BSD-3-Clause License
